### ISSUE TITLE
Moving windows between screens doesn't work.

### ISSUE THREAD

**Issue by adamcik** [brockgr/chrometile#4]
I get the following traceback from the background page:

```
background.js:311 Uncaught (in promise) TypeError: allDisplays[n].area is not a function
    at resolve (chrome-extension://aikaaejchodabfpkipfonnekofgepakh/background.js:311:36)
    at new Promise (<anonymous>)
    at moveDisp (chrome-extension://aikaaejchodabfpkipfonnekofgepakh/background.js:309:12)
    at Map (chrome-extension://aikaaejchodabfpkipfonnekofgepakh/background.js:351:58)
    at chrome-extension://aikaaejchodabfpkipfonnekofgepakh/background.js:360:61
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at dispatchArgs (extensions::event_bindings:260:26)
    at dispatchEvent (extensions::event_bindings:269:7)
```

Editing this line to not call `.area()` in the developer tools seems to fix the problem. Not sure if this problem has been here all along or if Chrome display APIs changed at some point.

**Comment by adamcik** [comment]
And for reference, this was on a pixelbook running:

```
Google Chrome | 72.0.3611.0 (Official Build) dev (64-bit)
Revision | 1e634547d9fe9e14027b66ae5d1e938b14a7ddf0-refs/branch-heads/3611@{#1}
Platform | 11265.0.0 (Official Build) dev-channel eve
```
